openapi: 3.0.0
info:
  title: Regate API
  version: "1.0"
servers: 
- url: https://api.regate.io/v1
security:
  - bearerAuth: []
paths:
  /invoices:
    get:
      description: Retrieve an invoice
      operationId: getInvoice
      tags:
        - invoice
      parameters:
        - name: filter
          in: query
          description: A JSON array of objects, allowing you to filter invoices on specific attributes (date, status, amount, etc.). Different attributes allow for different operators, e.g. less than, greater than, equals, etc. Refer to our [documentation](#need_link) for detailed information.
          required: false
          schema:
            type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OutputInvoice"
        400:
          description: Bad request. API request was not correctly formatted.
          $ref: "#/components/responses/BadRequest"
        401:
          description: Unauthorized request. Token is missing or is invalid.
          $ref: "#/components/responses/Unauthorized"
        403:
          description: Authentication was successful, but the user does not have permission to access the URL.
          $ref: "#/components/responses/Forbidden"
        500:
          description: Server error, please try again later.
          $ref: "#/components/responses/ServerError"

    post:
      tags:
      - Invoice
      description: Create a new invoice.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateInvoice'
      responses:
        201:
          description: Invoice succesfully created.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutputInvoice"
        400:
          description: Bad request. API request was not correctly formatted.
          $ref: "#/components/responses/BadRequest"
        401:
          description: Unauthorized request. Token is missing or is invalid.
          $ref: "#/components/responses/Unauthorized"
        403:
          description: Authentication was successful, but the user does not have permission to access the URL.
          $ref: "#/components/responses/Forbidden"
        500:
          description: Server error, please try again later.
          $ref: "#/components/responses/ServerError"

  /invoices/{invoice_id}:
    get:
      description: Retrieve a single invoice.
      parameters:
      - name: invoice_id
        in: path
        required: true
        description: Unique ID assigned to this invoice.
        schema:
          type: string
      responses:
        200:
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/OutputInvoice"
        400:
          description: Bad request. API request was not correctly formatted.
          $ref: "#/components/responses/BadRequest"
        401:
          description: Unauthorized request. Token is missing or is invalid.
          $ref: "#/components/responses/Unauthorized"
        403:
          description: Authentication was successful, but the user does not have permission to access the URL.
          $ref: "#/components/responses/Forbidden"
        404:
          description: Not found.
          $ref: "#/components/responses/NotFound"
        500:
          description: Server error, please try again later.
          $ref: "#/components/responses/ServerError"


components:

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT


  responses:
    BadRequest:
      description: "Bad input. See ErrorMessage for more information."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"
    Unauthorized:
      description: "Your API credentials are not valid. Please review them."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"
    Forbidden:
      description: "You don't have permission to access this URL."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"
    NotFound:
      description: "URL does not exist."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"
    ServerError:
      description: "Something wrong happened on our side, sorry for the inconvenience."
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorMessage"


  schemas:
    CreateInvoice:
      type: object
      required:
      - company_id
      - customer_id
      - deposit_in_cents
      - deposit_currency
      - invoice_date
      - invoice_due_date
      properties:
        company_id:
          type: string
          description: ID of the company.
        customer_id:
          type: string
          description: ID of the customer, linked to this invoice.
        customer_reference:
          type: string
        deposit_in_cents:
          type: integer
          description: The deposit amount (in cents) that has already been paid.
        deposit_currency:
          type: string
          description: The currency of the already paid deposit amount.
        footer_text:
          type: string
          description: The footer text on the invoice.
        invoice_date:
          type: string
          description: The date, on which the invoice was issued.
        invoice_delivery_date:
          type: string
          description: The date, on which the invoice was delivered.
        invoice_due_date:
          type: string
          description: The date, on which the invoice is due.
        payment_method_details:
          type: string
        payment_terms:
          type: integer
        peyment_terms_text:
          type: string
        purchase_order_text:
          type: string
        recurrence_attributes:
          type: object
          description: **Optional** An object containing attributes, describing the details of any recurrence of payment linked to this invoice.
          properties:
            action:
              type: string
            currency:
              type: string
            id:
              type: string
            recurrence_interval:
              type: string
            recurrence_amount:
              type: integer
            active_from:
              type: string
            active_to:
              type: string
            document_template_id:
              type: string
        payment_reference:
          type: string
        subject_text:
          type: string
        transaction_lines_attributes:
          type: array
          description: An array of objects, each describing a transaction line within the invoice.
          items:
            product_id:
              type: string
              description: Unique ID of the product for this line within the invoice.
            quantity_in_cents:
              type: integer
              description: Indicates the amount of items in cents. Divide by 100 to receive the proper amount.
            tax_financial_account_id:
              type: string
            title:
              type: string
              description: The name of the product on this transaction line.
            total_price_in_cents:
              type: integer
              description: The total price for the products in this line in cents. Divide by 100 to receive the proper amount in the specified currency.
            total_price_currency:
              type: string
            unit_price_cents: 
              type: integer
              description: The price for a single product described in this transaction line (in cents). Divide by 100 to receive the proper amount in the specified currency.
            unit_price_currency: 
              type: string
        invoice_type:
          type: string
          required: true
          description: Type of invoice.
        vat_paid: 
          type: string        
        



    OutputInvoice:
      type: object
      description: An object containing the attributes for an invoice.
      properties:
        asd:
          type: integer




    ErrorMessage:
      properties:
        ErrorMessage:
          description: Error message describing the error.
          type: string
        ErrorCode:
          description: Error code of the error.
          type: string
        ErrorRelatedTo:
          description: A list of properties to which the error relates.
          type: array
          items:
            type: string
        ErrorIdentifier:
          description: Error identifier used for tracing.
          type: string
          format: uuid
        StatusCode:
          description: Status code for this request.
          type: integer
